import React from 'react';
import { Link } from 'react-router-dom';
import { FaFire, FaInfoCircle, FaArrowLeft } from 'react-icons/fa';

const About = () => {
  return (
    <div className="container mx-auto px-4 py-8 max-w-4xl">
      <Link to="/" className="flex items-center space-x-2 text-primary hover:text-primary-dark mb-8">
        <FaArrowLeft />
        <span>Back to Home</span>
      </Link>
      
      <header className="text-center mb-12">
        <div className="flex justify-center items-center space-x-3 mb-4">
          <h1 className="text-4xl font-bold text-primary">About Resume Roaster</h1>
          <FaFire className="text-3xl text-accent" />
        </div>
        <p className="text-xl text-gray-600">
          Where your resume meets its worst nightmare
        </p>
      </header>

      <main className="space-y-8">
        <section className="card">
          <div className="flex items-center space-x-3 mb-4">
            <FaInfoCircle className="text-2xl text-primary" />
            <h2 className="text-2xl font-bold">What is Resume Roaster?</h2>
          </div>
          <p className="text-gray-700 mb-4">
            Resume Roaster is a fun tool that uses AI to provide humorous, sarcastic feedback on your resume or project descriptions. 
            Whether you're looking for a laugh or some brutally honest feedback wrapped in humor, our roasts can help you see your 
            professional content from a different perspective.
          </p>
          <p className="text-gray-700">
            Powered by Google's Gemini AI, our roasts range from mild constructive criticism to scorching burns that will make you 
            question your career choices (in the most entertaining way possible).
          </p>
        </section>

        <section className="card">
          <h2 className="text-2xl font-bold mb-4">Roast Levels</h2>
          <div className="space-y-6">
            <div className="flex items-start space-x-4">
              <div className="bg-green-100 p-2 rounded-full">
                <FaFire className="text-green-500" />
              </div>
              <div>
                <h3 className="text-xl font-semibold">Mild Roast</h3>
                <p className="text-gray-700">
                  A gentle critique with constructive feedback. We'll point out areas for improvement while being somewhat nice about it.
                  Perfect for those who want helpful feedback with just a touch of sarcasm.
                </p>
              </div>
            </div>
            
            <div className="flex items-start space-x-4">
              <div className="bg-yellow-100 p-2 rounded-full">
                <div className="flex">
                  <FaFire className="text-yellow-500" />
                  <FaFire className="text-yellow-500" />
                </div>
              </div>
              <div>
                <h3 className="text-xl font-semibold">Spicy Roast</h3>
                <p className="text-gray-700">
                  A stronger critique with sharp humor. We'll be more direct about the flaws in your content, 
                  with creative analogies and references that might make you laugh... or cry.
                </p>
              </div>
            </div>
            
            <div className="flex items-start space-x-4">
              <div className="bg-red-100 p-2 rounded-full">
                <div className="flex">
                  <FaFire className="text-red-500" />
                  <FaFire className="text-red-500" />
                  <FaFire className="text-red-500" />
                </div>
              </div>
              <div>
                <h3 className="text-xl font-semibold">Extra Burn</h3>
                <p className="text-gray-700">
                  A scorching critique with no mercy. We'll pull out all the stops for a comedic takedown of your content.
                  Expect exaggerated flaws, pop culture references, and maybe one tiny constructive suggestion buried in mockery.
                  Not for the faint of heart!
                </p>
              </div>
            </div>
          </div>
        </section>

        <section className="card">
          <h2 className="text-2xl font-bold mb-4">Disclaimer</h2>
          <p className="text-gray-700">
            Resume Roaster is meant for entertainment purposes. The roasts are generated by AI and should be taken with a grain of salt.
            While they might contain useful feedback, they're primarily designed to make you laugh. 
            We're not responsible for any existential crises that may result from our roasts.
          </p>
        </section>
      </main>
    </div>
  );
};

export default About; 